### ISSUE TITLE
Баги 

### ISSUE THREAD

**Issue by yuchiko** [ivadimko/template-mogo#1]
1. При инициализации не по центру, после клика только нормально встают http://joxi.ru/zANkOjDHBLEeRr
2. Ошибки в консоли http://joxi.ru/n2YOqVkFo1Mqyr
3. А почему меню не переносит на секции ? http://joxi.ru/Vm6dnRQSDWywEA
4. с неймингом еще поработай, слишком длинное название `storyaboutus` и еще и составное

**Comment by vadim-ilchenko** [comment]
1. Когда появляется баг? У меня все ок.
2. Пофиксил. Проблема была в объявлении `callback` по окончанию подсчета цифр.
3. Пофиксил.
4. Согласен. Переделал, что нашел. 

[RESULT](https://ivadimko.github.io/template-mogo/)
